name: document

on: 
  push:
    branches:
    - master

jobs:
  document:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.4.1
      with: 
        ssh-private-key: ${{ secrets.docsRepoToken }}
    - name: fetch docs repo
      run: git clone --depth 1 git@github.com:acdh-oeaw/arche-docs.git docsrepo
    - name: generate docs
      run: |
        rm -fR docsrepo/arche-lib-schema/*
        docker run --rm -v $(pwd):/data phpdoc/phpdoc:3 -d src -t docsrepo/arche-lib-schema
    - name: commit docs
      run: |
        cd docsrepo
        git config user.email "workflow@github.actions"
        git config user.name "Github Actions Workflow"
        git add arche-lib-schema/*
        git commit -a -m 'Documentation updated' || true
        git push origin || true
